import { getHomeTRPCClient, getTRPCClient } from '@/lib/trpc';
import {
  acceptInboundChannelChain,
  encryptChannelMessage as encryptChannelWithChain,
  decryptChannelMessage as decryptChannelWithChain,
  getOrCreateOutboundChannelChain,
  hasChannelChain,
  MissingChainError,
  rotateOutboundChannelChain
} from './sender-keys';
import {
  acceptInboundDmChain,
  encryptDmGroupMessage as encryptDmGroupWithChain,
  decryptDmGroupMessage as decryptDmGroupWithChain,
  getOrCreateOutboundDmChain,
  hasDmChain,
  MissingDmChainError,
  rotateOutboundDmChain
} from './dm-sender-keys';
import {
  captureOwnPlaintextByCiphertext,
  clearAllOwnPlaintexts,
  getPersistedOwnPlaintextById,
  persistOwnPlaintextById,
  takeOwnPlaintextByCiphertext
} from './plaintext-cache';
import type { ChainKind, SenderKeyDistribution } from './sender-key-chain';
import { decodeWire } from './sender-key-chain';

/**
 * Phase B sender-key wire = base64(version 0x02 || senderKeyId || iter
 * || iv || ct || sig). Pairwise libsignal envelope is JSON
 * `{type,body}`. Detecting which we have lets the receive path
 * dispatch correctly even after a group→1:1 demotion (where current
 * channel state says "1:1" but historical messages were encrypted
 * under a sender-key chain).
 */
export function isSenderKeyWire(content: string): boolean {
  try {
    decodeWire(content);
    return true;
  } catch {
    return false;
  }
}
import {
  buildSession,
  decryptMessage,
  encryptMessage,
  generateKeys,
  generateOneTimePreKeys,
  generateSignedPreKey,
  getIdentityPublicKey,
  hasKeys,
  hasSession
} from './signal-protocol';
import {
  getActiveStore,
  getStoreForInstance,
  signalStore,
  type SignalProtocolStore
} from './store';
import {
  presentIdentityChange,
  UntrustedIdentityError
} from './identity-change-dispatch';
import {
  retryFailedChannelDecrypts,
  retryFailedDmDecrypts
} from './decrypt-retry';
import type { E2EEPlaintext, PreKeyBundle } from './types';

export { UntrustedIdentityError } from './identity-change-dispatch';

const OTP_REPLENISH_THRESHOLD = 25;
const OTP_REPLENISH_COUNT = 100;
const INITIAL_OTP_BATCH_NEXT_ID = OTP_REPLENISH_COUNT + 1;
// Rotate signedPreKey weekly. Long-term signing key compromise is the
// main thing this guards against; weekly cadence is what Signal docs
// recommend and is well below the time-to-compromise of an attacker
// with read-only access to a leaked DB snapshot.
const SIGNED_PRE_KEY_ROTATE_INTERVAL_MS = 7 * 24 * 60 * 60 * 1000;

const KIND_CHANNEL: ChainKind = 'channel';
const KIND_DM: ChainKind = 'dm';

/**
 * Reserve the next contiguous block of OTP key IDs for `store`. Persists
 * the new high-water mark to IDB BEFORE returning the start id so a page
 * reload mid-replenish can't re-use ids the server already accepted.
 *
 * On a fresh store with no counter recorded, seeds at
 * `INITIAL_OTP_BATCH_NEXT_ID` (101) — picks up after the initial
 * batch of 100 generated by `generateKeys()`.
 */
async function reserveOtpKeyIdRange(
  store: SignalProtocolStore,
  count: number
): Promise<number> {
  const current =
    (await store.getNextOtpKeyId()) ?? INITIAL_OTP_BATCH_NEXT_ID;
  await store.setNextOtpKeyId(current + count);
  return current;
}

// --- Channel Member Cache ---
// Cache of channel → member descriptors fetched from the active
// server's getVisibleUserDescriptors route. Each descriptor carries
// the federation-aware fields needed to address recipients across
// instances:
//   - id              local id ON THE ACTIVE SERVER (host's view)
//   - name            display name on host
//   - publicId        stable cross-instance identifier
//   - instanceDomain  user's home — used to route the SKDM
//                     dispatch and resolve to a home-local id for
//                     the Signal session
type ChannelMemberDescriptor = {
  id: number;
  name: string;
  publicId: string;
  instanceDomain: string;
};
const channelMemberCache = new Map<number, ChannelMemberDescriptor[]>();

async function getChannelMemberDescriptors(
  channelId: number
): Promise<ChannelMemberDescriptor[]> {
  const cached = channelMemberCache.get(channelId);
  if (cached) return cached;

  const trpc = getTRPCClient();
  if (!trpc) return [];
  const descriptors = await trpc.channels.getVisibleUserDescriptors.query({
    channelId
  });
  channelMemberCache.set(channelId, descriptors);
  return descriptors;
}

export function invalidateChannelMembers(channelId?: number): void {
  if (channelId !== undefined) {
    channelMemberCache.delete(channelId);
  } else {
    channelMemberCache.clear();
  }
}

/**
 * Initialize E2EE on the home instance. Called once after auth.
 * If keys exist, replenishes OTPs. If not, does nothing — keys are
 * set up on demand via ensureE2EEKeys() when the user tries to
 * participate in an encrypted channel/DM.
 */
export async function initE2EE(): Promise<void> {
  const keysExist = await hasKeys();

  if (keysExist) {
    await replenishOTPsIfNeeded();
    await rotateSignedPreKeyIfNeeded(signalStore);
  }
}

/**
 * Set up E2EE keys. Called by the setup modal after the user chooses.
 * - mode 'restore': restores from server backup using passphrase
 * - mode 'generate': generates fresh keys and registers with server
 */
export async function setupE2EEKeys(
  mode: 'restore' | 'generate',
  passphrase?: string
): Promise<void> {
  if (mode === 'restore') {
    if (!passphrase) throw new Error('Passphrase required for restore');
    const { restoreBackupFromServer } = await import('./key-backup');
    await restoreBackupFromServer(passphrase);
    await finalizeRestoredKeys();
  } else {
    const trpc = getHomeTRPCClient();
    if (!trpc) throw new Error('Not connected');
    const keys = await generateKeys(OTP_REPLENISH_COUNT);
    await trpc.e2ee.registerKeys.mutate(keys);
    // Seed the persistent OTP cursor and signed-prekey rotation
    // bookkeeping so the very first reload doesn't reset to 101 and
    // collide with the initial batch we just registered.
    await signalStore.setNextOtpKeyId(INITIAL_OTP_BATCH_NEXT_ID);
    await signalStore.setSignedPreKeyId(1);
    await signalStore.setSignedPreKeyRotatedAt(Date.now());
  }
}

/**
 * Post-restore reconciliation. Must run after IDB has been written from
 * a backup blob (server backup OR local file import). Without this the
 * server keeps the identity registered by whatever ran *between* the
 * backup and the restore — typically a regen — which leaves peers and
 * server out of sync with our restored IDB:
 *
 *  - Peers store the regen-era sender key for us; we encrypt with the
 *    backup-era one. AES-GCM tag mismatch.
 *  - Peers fetching getPreKeyBundle(us) get the regen prekey-bundle and
 *    encrypt distributions to it; we try to open them with the restored
 *    identity. X3DH agreement fails.
 *  - The decrypt-failure retry path (fetchAndProcessPendingSenderKeys)
 *    keeps grabbing rows that were encrypted to the wrong identity.
 *
 * Steps:
 *  1. Wipe all Signal sessions — restored sessions describe a ratchet
 *     state peers no longer agree with, so we have to rebuild via X3DH
 *     next encrypt.
 *  2. Wipe all Phase B chains — for the same reason; peers will re-SKDM
 *     us under the restored identity once they receive E2EE_IDENTITY_RESET.
 *  3. Re-register the restored identity with a fresh signed-prekey + OTP
 *     batch signed under it. Server flips back to the restored identity,
 *     clears stale e2ee_sender_keys rows, and broadcasts
 *     E2EE_IDENTITY_RESET to peers (who run handlePeerIdentityReset and
 *     re-distribute their sender keys to our restored prekey-bundle).
 *  4. Push our (restored) sender keys back to peers, overwriting whatever
 *     they had from the regen-era distribution. Sessions rebuild lazily
 *     in ensureSession because step 1 cleared them.
 *
 * Suppresses our own tab from auto-reloading on the E2EE_IDENTITY_RESET
 * broadcast we trigger here.
 */
export async function finalizeRestoredKeys(): Promise<void> {
  await signalStore.clearAllSessions();
  await signalStore.clearAllChains();
  // Own-message cache is identity-scoped — restoring a different
  // identity must not surface plaintexts encrypted under the prior
  // identity's chains as if they were the restored identity's.
  await clearAllOwnPlaintexts();

  const trpc = getHomeTRPCClient();
  if (!trpc) {
    // No connection — restore wrote IDB but we can't sync the server now.
    // Whatever runs initE2EE later will at least replenish OTPs against
    // the (still-stale) server identity, which is no worse than today.
    return;
  }

  const identityPubKey = await getIdentityPublicKey();
  const registrationId = await signalStore.getLocalRegistrationId();
  if (!identityPubKey || registrationId === undefined) {
    throw new Error('Restored backup is missing an identity key');
  }

  // Fresh signed prekey + OTPs signed under the restored identity.
  // registerKeys server-side replaces signedPreKeys + OTPs unconditionally,
  // so reusing the backup's prekeys would be redundant work.
  const signedPreKey = await generateSignedPreKey(1);
  await signalStore.setSignedPreKeyId(1);
  await signalStore.setSignedPreKeyRotatedAt(Date.now());
  const otpStartId = await reserveOtpKeyIdRange(
    signalStore,
    OTP_REPLENISH_COUNT
  );
  const oneTimePreKeys = await generateOneTimePreKeys(
    otpStartId,
    OTP_REPLENISH_COUNT
  );

  setLocalResetFlag(true);
  try {
    await trpc.e2ee.registerKeys.mutate({
      identityPublicKey: identityPubKey,
      registrationId,
      signedPreKey,
      oneTimePreKeys
    });

    await redistributeOwnSenderKeys();
  } finally {
    setLocalResetFlag(false);
  }
}

// Singleton state for the ensureE2EEKeys gate
let pendingSetup: Promise<void> | null = null;

/**
 * Gate that ensures E2EE keys exist before proceeding.
 * If keys exist, resolves immediately. If not, dispatches an
 * `e2ee-setup-needed` CustomEvent with resolve/reject callbacks
 * so the UI can show the setup modal. Returns a Promise that
 * resolves when the user completes setup or rejects on cancel.
 * Singleton: only one modal opens even if multiple operations trigger.
 */
export async function ensureE2EEKeys(): Promise<void> {
  if (await hasKeys()) return;

  if (pendingSetup) return pendingSetup;

  pendingSetup = new Promise<void>((resolve, reject) => {
    window.dispatchEvent(
      new CustomEvent('e2ee-setup-needed', {
        detail: { resolve, reject }
      })
    );
  }).finally(() => {
    pendingSetup = null;
  });

  return pendingSetup;
}

/**
 * Initialize E2EE on a federated instance by reusing the home identity.
 * Copies the home identity key pair into the per-instance store (which
 * keeps its own sessions and sender keys to avoid user-ID collisions),
 * then generates a fresh signed pre-key and OTPs and registers them
 * on the remote server.
 */
export async function initE2EEForInstance(domain: string): Promise<void> {
  // Don't prompt for key setup — this is a background init.
  // If the user hasn't generated keys, silently skip.
  if (!(await hasKeys())) return;

  const store = getStoreForInstance(domain);
  const keysExist = await hasKeys(store);

  // Detect if the home identity changed since we last copied it.
  // If so, wipe the stale per-instance store and re-register.
  const needsReRegister =
    keysExist && (await identityDrifted(store, signalStore));

  if (!keysExist || needsReRegister) {
    if (needsReRegister) {
      console.log(`[E2EE] Home identity changed — re-registering on ${domain}`);
      await store.clearAll();
    }

    // Copy the home identity (same key pair + registration ID) into the
    // per-instance store so all servers see the same cryptographic identity.
    await store.copyIdentityFrom(signalStore);

    // Generate a fresh signed pre-key (signed with the shared identity)
    const signedPreKey = await generateSignedPreKey(1, store);
    await store.setSignedPreKeyId(1);
    await store.setSignedPreKeyRotatedAt(Date.now());

    // Generate fresh OTPs for this instance (each server consumes independently)
    const otpStartId = await reserveOtpKeyIdRange(store, OTP_REPLENISH_COUNT);
    const oneTimePreKeys = await generateOneTimePreKeys(
      otpStartId,
      OTP_REPLENISH_COUNT,
      store
    );

    // Read public identity for registration
    const identityPubKey = await getIdentityPublicKey(store);
    const registrationId = await store.getLocalRegistrationId();

    // getTRPCClient() routes to remote when activeInstanceDomain is set
    const trpc = getTRPCClient();
    if (!trpc) return;
    await trpc.e2ee.registerKeys.mutate({
      identityPublicKey: identityPubKey!,
      registrationId: registrationId!,
      signedPreKey,
      oneTimePreKeys
    });
    console.log(`[E2EE] Registered home identity on federated instance: ${domain}`);
    return;
  }

  // Check OTP count and replenish on remote if needed
  const remote = getTRPCClient();
  await replenishOTPsIfNeeded(store, remote);
  await rotateSignedPreKeyIfNeeded(store, remote);
}

/**
 * Compare the identity public key in two stores.
 * Returns true if they differ (i.e. the home key was regenerated).
 */
async function identityDrifted(
  instanceStore: SignalProtocolStore,
  homeStore: SignalProtocolStore
): Promise<boolean> {
  const instanceKey = await getIdentityPublicKey(instanceStore);
  const homeKey = await getIdentityPublicKey(homeStore);
  if (!instanceKey || !homeKey) return true;
  return instanceKey !== homeKey;
}

/**
 * Check the server OTP count and replenish if below threshold.
 */
async function replenishOTPsIfNeeded(
  store?: SignalProtocolStore,
  trpc?: ReturnType<typeof getHomeTRPCClient>
): Promise<void> {
  const t = trpc ?? getHomeTRPCClient();
  if (!t) return;
  const count = await t.e2ee.getPreKeyCount.query();

  if (count < OTP_REPLENISH_THRESHOLD) {
    const targetStore = store ?? signalStore;
    const otpStartId = await reserveOtpKeyIdRange(
      targetStore,
      OTP_REPLENISH_COUNT
    );
    const newKeys = await generateOneTimePreKeys(
      otpStartId,
      OTP_REPLENISH_COUNT,
      targetStore
    );
    await t.e2ee.uploadOneTimePreKeys.mutate({
      oneTimePreKeys: newKeys
    });
  }
}

/**
 * Generate a new signed-prekey for `store` if the last rotation is
 * older than `SIGNED_PRE_KEY_ROTATE_INTERVAL_MS`. The keyId increments
 * monotonically so libsignal can keep the old signed-prekey around for
 * sessions still mid-handshake while peers catch up to the new bundle.
 *
 * On a store that has no recorded rotation timestamp (i.e. anyone who
 * registered before this code shipped, or anyone whose registerKeys
 * baseline used keyId=1), this triggers an initial rotation — gets
 * everyone onto the rotation cadence on first boot post-deploy.
 *
 * No-op if no tRPC client is connected (initial connect not yet done).
 */
async function rotateSignedPreKeyIfNeeded(
  store: SignalProtocolStore,
  trpc?: ReturnType<typeof getHomeTRPCClient>
): Promise<void> {
  const t = trpc ?? getHomeTRPCClient();
  if (!t) return;

  const rotatedAt = await store.getSignedPreKeyRotatedAt();
  if (
    rotatedAt !== undefined &&
    Date.now() - rotatedAt < SIGNED_PRE_KEY_ROTATE_INTERVAL_MS
  ) {
    return;
  }

  const currentId = (await store.getSignedPreKeyId()) ?? 1;
  const nextId = currentId + 1;

  try {
    const signedPreKey = await generateSignedPreKey(nextId, store);
    await t.e2ee.rotateSignedPreKey.mutate(signedPreKey);
    await store.setSignedPreKeyId(nextId);
    await store.setSignedPreKeyRotatedAt(Date.now());
  } catch (err) {
    console.warn('[E2EE] signedPreKey rotation failed:', err);
  }
}

/**
 * Look up a user's federation status from Redux. `_identity` is set
 * to `name@domain` for federated users (joined-user query in
 * apps/server/src/db/queries/users.ts) and undefined for local users.
 *
 * Best-effort: if Redux isn't ready or the user isn't in any
 * loaded slice, default to local. A wrong guess is self-correcting
 * — the wrong-route fetch returns null and the caller surfaces it
 * as a clear "encrypted DM unavailable" failure per Decision 2.
 */
async function isUserFederated(userId: number): Promise<boolean> {
  try {
    const { store: reduxStore } = await import('@/features/store');
    const state = reduxStore.getState();
    const user =
      state.server.users.find((u) => u.id === userId) ??
      state.friends.friends.find((f) => f.id === userId);
    return !!user?._identity && user._identity.includes('@');
  } catch {
    return false;
  }
}

/**
 * Ensure we have a session with a user. If not, fetch their pre-key bundle
 * and establish one via X3DH.
 *
 * When `verifyIdentity` is true (same-instance only), checks whether
 * the remote user's server-side identity key still matches what we
 * have stored locally. If it changed (key reset), the stale session
 * is cleared and a fresh one is built. This avoids encrypting with
 * an old session that the reset user can't decrypt.
 *
 * For federated users (Phase D / D2), the bundle is fetched via
 * `e2ee.getFederatedPreKeyBundle` — the home server proxies the
 * request to the recipient's instance and verifies the signed
 * response (Phase D / D0). The verifyIdentity branch is skipped:
 * D3's identity-rotation broadcast handles cross-instance rotation;
 * stale federated sessions surface the identity-changed modal on
 * the next decrypt attempt.
 */
async function ensureSession(
  userId: number,
  opts?: {
    store?: SignalProtocolStore;
    trpc?: ReturnType<typeof getHomeTRPCClient>;
    verifyIdentity?: boolean;
  }
): Promise<void> {
  const s = opts?.store ?? signalStore;
  const trpc = opts?.trpc ?? getHomeTRPCClient();
  if (!trpc) throw new Error('Not connected');

  const federated = await isUserFederated(userId);

  if (await hasSession(userId, s)) {
    if (opts?.verifyIdentity && !federated) {
      const serverKey = await trpc.e2ee.getIdentityPublicKey.query({ userId });
      const localKey = await s.getStoredIdentityKey(userId);

      if (serverKey && localKey && serverKey !== localKey) {
        // Identity changed — clear stale session so we rebuild below
        await s.clearUserSession(userId);
      } else {
        return;
      }
    } else {
      return;
    }
  }

  const bundle = federated
    ? await trpc.e2ee.getFederatedPreKeyBundle.query({ userId })
    : await trpc.e2ee.getPreKeyBundle.query({ userId });

  if (!bundle) {
    // Decision 2: hard fail. The thrown message is user-facing —
    // it surfaces verbatim through `getTrpcError` into the
    // composer's toast on a failed send. Don't include internal
    // userIds; do say what failed and (when federated) why.
    throw new Error(
      federated
        ? "Encrypted DM unavailable — the recipient's instance is unreachable or hasn't published encryption keys."
        : "Encrypted DM unavailable — the recipient hasn't set up encryption yet."
    );
  }

  const typedBundle = bundle as PreKeyBundle;
  try {
    await buildSession(userId, typedBundle, s);
  } catch (err) {
    // Phase C: TOFU mismatch — libsignal throws this exact string from
    // session-builder.js:45 when isTrustedIdentity returns false.
    // Surface the modal; on Accept, re-pin and retry the same bundle.
    // On Block/Cancel, propagate as UntrustedIdentityError so callers
    // can mark the in-flight operation as failed.
    if (err instanceof Error && err.message === 'Identity key changed') {
      const accepted = await presentIdentityChange(
        userId,
        typedBundle.identityPublicKey,
        s
      );
      if (accepted) {
        await buildSession(userId, typedBundle, s);
        return;
      }
      throw new UntrustedIdentityError(userId, typedBundle.identityPublicKey);
    }
    throw err;
  }
}

/**
 * Encrypt a DM message payload for a specific recipient.
 * Establishes a session first if needed.
 * Always uses home instance store + home tRPC.
 */
export async function encryptDmMessage(
  recipientUserId: number,
  payload: E2EEPlaintext
): Promise<string> {
  await ensureE2EEKeys();
  await ensureSession(recipientUserId, { verifyIdentity: true });
  const plaintext = JSON.stringify(payload);
  return encryptMessage(recipientUserId, plaintext);
}

/**
 * Decrypt a DM message received from a specific sender.
 * Always uses home instance store.
 *
 * If decryption fails (e.g. the sender reset their keys and the local session
 * is stale), clears the stale session and retries once. The retry allows the
 * Signal Protocol library to process the PreKeyWhisperMessage with a clean
 * slate and establish a fresh session.
 */
export async function decryptDmMessage(
  senderUserId: number,
  encryptedContent: string
): Promise<E2EEPlaintext> {
  try {
    const plaintext = await decryptMessage(senderUserId, encryptedContent);
    return JSON.parse(plaintext) as E2EEPlaintext;
  } catch (firstErr) {
    // Clear the stale session and retry — the message may be a
    // PreKeyWhisperMessage from a sender who regenerated keys.
    await signalStore.clearUserSession(senderUserId);
    try {
      const plaintext = await decryptMessage(senderUserId, encryptedContent);
      return JSON.parse(plaintext) as E2EEPlaintext;
    } catch {
      // Re-throw the original error if retry also fails
      throw firstErr;
    }
  }
}

// --- Channel E2EE (Sender Keys, Phase B) ---

/**
 * Mark a peer as no longer covered by ANY of our chain distributions.
 * Triggered after a peer identity reset / reconnect — the next ensure*
 * pass will re-encrypt every active SKDM to the new prekey bundle.
 *
 * Persists asynchronously so callers can stay synchronous; failures
 * (e.g. IDB tear-down mid-write) are non-fatal and recover on the
 * next ensure pass via membership re-check.
 */
export function clearDistributedMember(userId: number): void {
  getActiveStore().clearChainDistributionForUser(userId).catch(() => {});
  signalStore.clearChainDistributionForUser(userId).catch(() => {});
}

/**
 * DM-channel-equivalent of clearDistributedMember. Same behavior; DM
 * group chains live in the home store only, so we only touch
 * signalStore.
 */
export function clearDmDistributedMember(userId: number): void {
  signalStore.clearChainDistributionForUser(userId).catch(() => {});
}

/**
 * Distribute the latest SKDM for a chain to every member who hasn't
 * received it yet. Used on initial chain creation, on rotation, and
 * on member-add events. Idempotent — re-running after a network blip
 * just re-targets the still-pending recipients.
 *
 * `getMembers` is supplied so this helper can serve both channels
 * (server-fetched authoritative member list) and DM groups (caller
 * passes the channel's stored member list).
 */
async function distributeChainToMembers(args: {
  kind: ChainKind;
  scopeId: number;
  ownUserId: number;
  store: SignalProtocolStore;
  trpc: ReturnType<typeof getHomeTRPCClient>;
  distribution: SenderKeyDistribution;
  getMembers: () => Promise<number[]>;
  send: (
    distributions: { toUserId: number; distributionMessage: string }[]
  ) => Promise<void>;
}): Promise<void> {
  if (!args.trpc) return;

  const members = await args.getMembers();
  const distributed = await args.store.getChainDistribution(
    args.kind,
    args.scopeId,
    args.distribution.senderKeyId
  );
  const distributedSet = new Set(distributed);
  const targets = members.filter(
    (id) => id !== args.ownUserId && !distributedSet.has(id)
  );
  if (targets.length === 0) return;

  // Each SKDM is encrypted to a recipient via X3DH. We batch the
  // encryption (10 in flight) to keep memory bounded but pipeline
  // round-trips on slow networks. The wire payload is the JSON form
  // of the chain's SenderKeyDistribution.
  const skdmPlaintext = JSON.stringify(args.distribution);
  const CONCURRENCY = 10;
  const wirePackets: { toUserId: number; distributionMessage: string }[] = [];

  for (let i = 0; i < targets.length; i += CONCURRENCY) {
    const chunk = targets.slice(i, i + CONCURRENCY);
    const results = await Promise.allSettled(
      chunk.map(async (memberId) => {
        await ensureSession(memberId, {
          store: args.store,
          trpc: args.trpc,
          verifyIdentity: true
        });
        const encrypted = await encryptMessage(
          memberId,
          skdmPlaintext,
          args.store
        );
        return { toUserId: memberId, distributionMessage: encrypted };
      })
    );
    for (const r of results) {
      if (r.status === 'fulfilled') {
        wirePackets.push(r.value);
      } else {
        console.warn('[E2EE] Failed to encrypt SKDM:', r.reason);
      }
    }
  }

  if (wirePackets.length === 0) return;

  try {
    await args.send(wirePackets);
    for (const p of wirePackets) distributedSet.add(p.toUserId);
    await args.store.setChainDistribution(
      args.kind,
      args.scopeId,
      args.distribution.senderKeyId,
      [...distributedSet]
    );
  } catch (err) {
    console.warn('[E2EE] Distribute mutation failed:', err);
  }
}

/**
 * Ensure we have an outbound chain for this channel and that the
 * latest SKDM has been delivered to every visible member. Generates
 * a fresh chain on first call. If the chain is marked dirty (B4
 * lazy-rotation marker, set on kick/leave), rotates first, clearing
 * the marker.
 *
 * Member list comes from the active server's
 * `channels.getVisibleUserDescriptors` route — which respects channel-
 * level permissions. The descriptors carry publicId + instanceDomain
 * so federated members on other instances can be addressed across
 * the wire (Phase E / E1).
 *
 * Pairwise SKDM sessions and sender chains live in the active-instance
 * store (Phase B/C scoping). For each member we resolve the
 * descriptor through the *home* tRPC to a home-local userId — for
 * local-only channels viewed from home, that's the same id the
 * descriptor already carries; for federated members, it's the
 * shadow user on home (created on demand). The home-resolved id
 * is the libsignal address; this is what makes the same federated
 * peer's session reusable across channels and DMs.
 */
export async function ensureChannelSenderKey(
  channelId: number,
  ownUserId: number,
  opts?: {
    store?: SignalProtocolStore;
    trpc?: ReturnType<typeof getTRPCClient>;
  }
): Promise<void> {
  if (!(await hasKeys(opts?.store))) return;
  const store = opts?.store ?? getActiveStore();
  const activeTrpc = opts?.trpc ?? getTRPCClient();
  const homeTrpc = getHomeTRPCClient();
  if (!activeTrpc || !homeTrpc) return;

  // Lazy rotation. A marker set by the kick/leave subscription
  // handlers means our current chain leaks to a now-removed member.
  // Bump senderKeyId, generate a fresh chain, clear the marker.
  // Distribution that follows targets only the *current* member list
  // — the kicked user is no longer visible, so the new SKDM never
  // reaches them.
  let chain;
  if (await store.isChainDirty(KIND_CHANNEL, channelId)) {
    chain = await rotateOutboundChannelChain(channelId, ownUserId, store);
    await store.clearChainDirty(KIND_CHANNEL, channelId);
    // Member list may be stale post-kick — drop the cache.
    invalidateChannelMembers(channelId);
  } else {
    chain = await getOrCreateOutboundChannelChain(channelId, ownUserId, store);
  }

  const descriptors = await getChannelMemberDescriptors(channelId);
  const distribution = chain.buildDistribution();
  const distributedSet = new Set(
    await store.getChainDistribution(
      KIND_CHANNEL,
      channelId,
      distribution.senderKeyId
    )
  );

  // Resolve every descriptor (except self) to a home-local userId.
  // For local-only channels viewed from home, the resolution returns
  // the same id the descriptor carries (the active server == home).
  // For federated members, resolveByDescriptor finds-or-creates the
  // shadow user on home so we have a stable libsignal address.
  type ResolvedTarget = ChannelMemberDescriptor & { homeUserId: number };
  const resolved: ResolvedTarget[] = [];
  for (const d of descriptors) {
    // The descriptor.id is the active-server-local id, which equals
    // ownUserId only when active server == home. Skip self by
    // publicId for federated viewing too — safer.
    try {
      const result = await homeTrpc.users.resolveByDescriptor.mutate({
        publicId: d.publicId,
        instanceDomain: d.instanceDomain,
        name: d.name
      });
      if (result.id === null) continue;
      if (result.id === ownUserId) continue;
      if (distributedSet.has(result.id)) continue;
      resolved.push({ ...d, homeUserId: result.id });
    } catch (err) {
      console.warn('[E2EE] resolveByDescriptor failed:', err);
    }
  }
  if (resolved.length === 0) return;

  // Each SKDM is encrypted to a recipient via X3DH. Concurrency-
  // bounded for memory; round-trips pipeline on slow networks.
  const skdmPlaintext = JSON.stringify(distribution);
  const CONCURRENCY = 10;
  type WirePacket = {
    toPublicId: string;
    toInstanceDomain: string;
    distributionMessage: string;
    homeUserId: number;
  };
  const wirePackets: WirePacket[] = [];

  for (let i = 0; i < resolved.length; i += CONCURRENCY) {
    const chunk = resolved.slice(i, i + CONCURRENCY);
    const results = await Promise.allSettled(
      chunk.map(async (target) => {
        await ensureSession(target.homeUserId, {
          store,
          trpc: homeTrpc,
          verifyIdentity: true
        });
        const encrypted = await encryptMessage(
          target.homeUserId,
          skdmPlaintext,
          store
        );
        return {
          toPublicId: target.publicId,
          toInstanceDomain: target.instanceDomain,
          distributionMessage: encrypted,
          homeUserId: target.homeUserId
        };
      })
    );
    for (const r of results) {
      if (r.status === 'fulfilled') {
        wirePackets.push(r.value);
      } else {
        console.warn('[E2EE] Failed to encrypt SKDM:', r.reason);
      }
    }
  }

  if (wirePackets.length === 0) return;

  try {
    await activeTrpc.e2ee.distributeSenderKeysBatch.mutate({
      channelId,
      senderKeyId: chain.state.senderKeyId,
      distributions: wirePackets.map((p) => ({
        toPublicId: p.toPublicId,
        toInstanceDomain: p.toInstanceDomain,
        distributionMessage: p.distributionMessage
      }))
    });
    for (const p of wirePackets) distributedSet.add(p.homeUserId);
    await store.setChainDistribution(
      KIND_CHANNEL,
      channelId,
      distribution.senderKeyId,
      [...distributedSet]
    );
  } catch (err) {
    console.warn('[E2EE] Distribute mutation failed:', err);
  }
}

/**
 * Proactively distribute our sender keys to a user that just came online,
 * for every E2EE channel we're a member of. Closes the gap between
 * "member joins / reconnects" and "first message send" so the new user
 * can decrypt messages immediately.
 */
export async function distributeSenderKeysToOnlineMember(
  joinedUserId: number,
  ownUserId: number,
  e2eeChannelIds: number[]
): Promise<void> {
  if (!ownUserId || joinedUserId === ownUserId) return;
  if (e2eeChannelIds.length === 0) return;
  if (!(await hasKeys())) return;

  // Forget that we've SKDM'd this peer in any of our channels — the
  // identity check inside ensureSession will detect any drift and
  // rebuild via X3DH before redistribution.
  clearDistributedMember(joinedUserId);

  for (const channelId of e2eeChannelIds) {
    try {
      await ensureChannelSenderKey(channelId, ownUserId);
    } catch (err) {
      console.warn(
        `[E2EE] Proactive key distribution failed for channel ${channelId}:`,
        err
      );
    }
  }
}

/**
 * Process a received sender-key distribution message from a peer.
 * The wire `distributionMessage` is a Signal envelope encrypting the
 * JSON-serialized `SenderKeyDistribution`. After X3DH-decryption we
 * persist an inbound chain at the embedded senderKeyId.
 *
 * Channel-side: uses the active store (federated channels live in
 * per-instance stores).
 */
export async function processIncomingSenderKey(
  channelId: number,
  fromUserId: number,
  distributionMessage: string
): Promise<void> {
  const store = getActiveStore();
  const decryptedJson = await decryptMessage(
    fromUserId,
    distributionMessage,
    store
  );
  const distribution = JSON.parse(decryptedJson) as SenderKeyDistribution;
  await acceptInboundChannelChain(channelId, fromUserId, distribution, store);
  // Phase B follow-up: SKDM finally landed — re-decrypt any messages
  // from this sender that arrived first and got stuck on the
  // "[Unable to decrypt]" placeholder.
  retryFailedChannelDecrypts(channelId, fromUserId).catch((err) => {
    console.warn('[E2EE] Channel retry-decrypt loop errored:', err);
  });
}

/**
 * Phase E / E1f — process a federated channel SKDM.
 *
 * Receiver flow: the sender's instance pubsub'd
 * E2EE_FEDERATED_SENDER_KEY_AVAILABLE on our home WS. Our handler
 * pulls the SKDM rows from the host (where they live) and routes
 * each to this function:
 *
 *   1. Decrypt the SKDM ciphertext using *home* signal store with
 *      the sender's home-resolved id. The ciphertext was encrypted
 *      via X3DH against keys we published on home — host store
 *      doesn't have our private prekeys.
 *   2. Store the resulting chain key in the host's *instance* store
 *      keyed by host-local (channelId, fromUserId), so the existing
 *      channel-message decrypt path (which runs in the active store
 *      of whatever instance the user is currently viewing) finds it
 *      when a channel message arrives.
 *
 * `fromHomePublicId` + `fromInstanceDomain` come from the enriched
 * `e2ee.getPendingSenderKeys` row. For federated senders,
 * fromInstanceDomain is the sender's home; for local-on-host senders
 * it's null (means "this host" — collapses to hostDomain).
 */
export async function processIncomingFederatedSenderKey(args: {
  hostDomain: string;
  hostChannelId: number;
  hostFromUserId: number;
  fromHomePublicId: string;
  fromInstanceDomain: string | null;
  distributionMessage: string;
}): Promise<void> {
  const homeTrpc = getHomeTRPCClient();
  if (!homeTrpc) return;

  const senderInstanceDomain =
    args.fromInstanceDomain ?? args.hostDomain;

  const result = await homeTrpc.users.resolveByDescriptor.mutate({
    publicId: args.fromHomePublicId,
    instanceDomain: senderInstanceDomain
  });
  if (result.id === null) {
    console.warn(
      '[E2EE] could not resolve federated SKDM sender on home',
      args.fromHomePublicId
    );
    return;
  }
  const homeSenderUserId = result.id;

  // Decrypt with home store at the home-resolved sender address.
  const decryptedJson = await decryptMessage(
    homeSenderUserId,
    args.distributionMessage,
    signalStore
  );
  const distribution = JSON.parse(decryptedJson) as SenderKeyDistribution;

  // Store chain key in the host's per-instance store keyed by host-
  // local ids — so when a channel message from this sender arrives
  // while the user is viewing the host, the active-store decrypt
  // path finds the chain.
  const hostStore = getStoreForInstance(args.hostDomain);
  await acceptInboundChannelChain(
    args.hostChannelId,
    args.hostFromUserId,
    distribution,
    hostStore
  );

  retryFailedChannelDecrypts(args.hostChannelId, args.hostFromUserId).catch(
    (err) => {
      console.warn('[E2EE] Channel retry-decrypt loop errored:', err);
    }
  );
}

/**
 * Dedup map to prevent concurrent fetches for the same channel from racing.
 * Without this, the subscription handler and message decrypt handler can both
 * fire concurrent HTTP requests and redundantly process the same keys.
 */
const activeSenderKeyFetches = new Map<
  number | undefined,
  Promise<void>
>();

/**
 * Fetch and process all pending sender keys from the server.
 * Uses the active instance store + active tRPC client.
 * Concurrent calls for the same channelId share one in-flight request.
 */
export function fetchAndProcessPendingSenderKeys(
  channelId?: number
): Promise<void> {
  const existing = activeSenderKeyFetches.get(channelId);
  if (existing) return existing;

  const promise = doFetchAndProcessPendingSenderKeys(channelId).finally(() => {
    activeSenderKeyFetches.delete(channelId);
  });
  activeSenderKeyFetches.set(channelId, promise);
  return promise;
}

async function doFetchAndProcessPendingSenderKeys(
  channelId?: number
): Promise<void> {
  const store = getActiveStore();
  const trpc = getTRPCClient();
  if (!trpc) return;
  const pending = await trpc.e2ee.getPendingSenderKeys.query({
    channelId
  });

  const processedIds: number[] = [];

  for (const key of pending) {
    try {
      const decryptedJson = await decryptMessage(
        key.fromUserId,
        key.distributionMessage,
        store
      );
      const distribution = JSON.parse(decryptedJson) as SenderKeyDistribution;
      await acceptInboundChannelChain(
        key.channelId,
        key.fromUserId,
        distribution,
        store
      );
      processedIds.push(key.id);
      // Phase B follow-up: each accepted SKDM unlocks pre-stuck
      // messages from that (channelId, fromUserId). Fire and forget.
      retryFailedChannelDecrypts(key.channelId, key.fromUserId).catch(
        (err) => {
          console.warn('[E2EE] Channel retry-decrypt loop errored:', err);
        }
      );
    } catch (err) {
      console.warn(
        `[E2EE] Failed to process sender key from user ${key.fromUserId}:`,
        err
      );
    }
  }

  if (processedIds.length > 0) {
    try {
      await trpc.e2ee.acknowledgeSenderKeys.mutate({ ids: processedIds });
    } catch {
      // Non-fatal: keys will be re-fetched and deduped on next attempt
    }
  }
}

/**
 * Encrypt a channel message under our latest outbound chain. Captures
 * the plaintext into the own-message cache keyed by wire bytes so the
 * subscription echo can self-decrypt — sender-key chains advance on
 * every encrypt and can't be re-derived to read our own messages
 * back, unlike the symmetric AES Phase A used.
 */
export async function encryptChannelMessage(
  channelId: number,
  ownUserId: number,
  payload: E2EEPlaintext
): Promise<string> {
  await ensureE2EEKeys();
  const store = getActiveStore();
  const plaintext = JSON.stringify(payload);
  const wire = await encryptChannelWithChain(
    channelId,
    ownUserId,
    plaintext,
    store
  );
  captureOwnPlaintextByCiphertext(wire, plaintext);
  return wire;
}

/**
 * Decrypt a channel message. Loads the sender's chain at the
 * senderKeyId embedded in the wire — if missing, fetches pending
 * SKDMs (bounded exponential backoff up to ~3.5s) and retries.
 *
 * `messageId` is optional — when provided, the own-message cache
 * persists the plaintext keyed by id so reload survives. Live-path
 * subscription handlers always pass it; legacy callers may not.
 */
export async function decryptChannelMessage(
  channelId: number,
  fromUserId: number,
  encryptedContent: string,
  messageId?: number
): Promise<E2EEPlaintext> {
  // Own-message fast path — see encryptChannelMessage. The wire bytes
  // we just captured during encrypt are exactly what comes back via
  // the subscription echo. Chain decrypt would throw "replay" because
  // the chain advanced past this iteration on encrypt.
  const cachedByCiphertext = takeOwnPlaintextByCiphertext(encryptedContent);
  if (cachedByCiphertext !== undefined) {
    if (messageId !== undefined) {
      void persistOwnPlaintextById(messageId, cachedByCiphertext);
    }
    return JSON.parse(cachedByCiphertext) as E2EEPlaintext;
  }
  if (messageId !== undefined) {
    const persisted = await getPersistedOwnPlaintextById(messageId);
    if (persisted !== undefined) {
      return JSON.parse(persisted) as E2EEPlaintext;
    }
  }

  const store = getActiveStore();
  const decoded = decodeWire(encryptedContent);
  const MAX_RETRIES = 3;
  const BASE_DELAY = 500;

  // Acquire the chain at this senderKeyId via bounded retries.
  for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
    if (await hasChannelChain(channelId, fromUserId, decoded.senderKeyId, store)) {
      break;
    }
    await fetchAndProcessPendingSenderKeys(channelId);
    if (await hasChannelChain(channelId, fromUserId, decoded.senderKeyId, store)) {
      break;
    }
    if (attempt < MAX_RETRIES) {
      await new Promise((r) =>
        setTimeout(r, BASE_DELAY * Math.pow(2, attempt))
      );
    }
  }

  let plaintext: string;
  try {
    plaintext = await decryptChannelWithChain(
      channelId,
      fromUserId,
      encryptedContent,
      store
    );
  } catch (err) {
    if (err instanceof MissingChainError) {
      // One last fetch attempt before giving up — the SKDM might
      // have arrived after the bounded-retry loop above ended.
      await fetchAndProcessPendingSenderKeys(channelId);
      plaintext = await decryptChannelWithChain(
        channelId,
        fromUserId,
        encryptedContent,
        store
      );
    } else {
      throw err;
    }
  }
  // Persist the plaintext keyed by messageId so future re-fetches
  // (history reload, navigation back, pagination) hit cache instead
  // of touching the chain. The chain advances on every decrypt and
  // can't re-derive a previously-decrypted iteration.
  if (messageId !== undefined) {
    void persistOwnPlaintextById(messageId, plaintext);
  }
  return JSON.parse(plaintext) as E2EEPlaintext;
}

// --- Key Reset Handling ---

/**
 * Flag to prevent the identity reset broadcast handler from reloading
 * the tab that initiated the reset. Set true before own key reset,
 * cleared after redistribution.
 */
let _isLocalReset = false;

export function setLocalResetFlag(value: boolean): void {
  _isLocalReset = value;
}

/**
 * Handle a peer (or own other-tab) identity reset broadcast.
 * - If userId matches our own and we didn't initiate it locally: reload
 *   (another tab reset our keys — IDB already updated, clear in-memory state)
 * - If peer: clear Signal session, clear our chain-distribution
 *   tracking for them (so the next encrypt re-SKDMs under their
 *   restored identity), then re-distribute own sender keys to them
 *   for all E2EE channels.
 */
export async function handlePeerIdentityReset(
  userId: number,
  // Phase D / D3 — federated rotations carry the new identity key
  // in the broadcast payload so the client doesn't have to round-
  // trip back through federation. Same-instance rotations leave
  // this undefined and the existing fetch path runs.
  newIdentityPublicKeyFromBroadcast?: string
): Promise<void> {
  const { store: reduxStore } = await import('@/features/store');
  const state = reduxStore.getState();
  const ownUserId = state.server.ownUserId;

  if (userId === ownUserId) {
    if (!_isLocalReset) {
      // Another tab reset our keys — reload to pick up new IDB state
      window.location.reload();
    }
    return;
  }

  // Phase C: peer just rotated their identity. Re-pin BEFORE we touch
  // sessions, so the SKDM-distribute below — which triggers libsignal
  // session re-establishment under the new identity — passes
  // `isTrustedIdentity` instead of throwing on the old pin.
  //
  // Phase D / D3: prefer the key embedded in the broadcast payload
  // (federated case). Fall back to the same-instance lookup when
  // missing. A lookup failure leaves the modal path (C4) to handle
  // the mismatch the next time a message goes through.
  const trpc = getHomeTRPCClient();
  let newIdentityKey: string | null = newIdentityPublicKeyFromBroadcast ?? null;
  if (!newIdentityKey && trpc) {
    try {
      newIdentityKey = await trpc.e2ee.getIdentityPublicKey.query({ userId });
    } catch (err) {
      console.warn(
        `[E2EE] Failed to refresh pinned identity for reset peer ${userId}:`,
        err
      );
    }
  }
  if (newIdentityKey) {
    try {
      await signalStore.acceptIdentityChange(userId, newIdentityKey);
      const active = getActiveStore();
      if (active !== signalStore) {
        await active.acceptIdentityChange(userId, newIdentityKey);
      }
    } catch (err) {
      console.warn(
        `[E2EE] Failed to apply new pinned identity for reset peer ${userId}:`,
        err
      );
    }
  }

  // Peer reset their keys — clear our stale session with them.
  // Always clear from the home store (DM sessions live there) AND the
  // active store (channel sender key sessions may live in a federated store).
  const store = getActiveStore();
  await store.clearUserSession(userId);
  if (store !== signalStore) {
    await signalStore.clearUserSession(userId);
  }
  clearDistributedMember(userId);

  // Invalidate member cache in case the reset user's permissions changed
  invalidateChannelMembers();

  const channelIds = trpc
    ? await trpc.e2ee.listMyE2eeChannelIds.query()
    : state.server.channels.filter((c) => c.e2ee).map((c) => c.id);

  for (const channelId of channelIds) {
    try {
      await ensureChannelSenderKey(channelId, ownUserId!);
    } catch (err) {
      console.warn(
        `[E2EE] Failed to re-distribute sender key to reset user ${userId} in channel ${channelId}:`,
        err
      );
    }
  }
}

/**
 * After own key reset: rotate every outbound chain (new senderKeyId)
 * and redistribute across home + every connected federated instance.
 * Each instance has its own SignalProtocolStore + its own ownUserId
 * for us, so we redistribute per-instance scoped to that instance's
 * tRPC client.
 *
 * Best-effort: a failing instance is logged and skipped so the rest
 * still get redistributed.
 */
export async function redistributeOwnSenderKeys(): Promise<void> {
  const { store: reduxStore } = await import('@/features/store');
  const { connectionManager } = await import('@/lib/connection-manager');
  const { appSliceActions } = await import('@/features/app/slice');
  const state = reduxStore.getState();

  invalidateChannelMembers();

  const redistributeForInstance = async (
    label: string,
    instanceTrpc: ReturnType<typeof getHomeTRPCClient>,
    instanceStore: SignalProtocolStore,
    instanceOwnUserId: number
  ) => {
    if (!instanceTrpc) return;
    let channelIds: number[];
    try {
      channelIds = await instanceTrpc.e2ee.listMyE2eeChannelIds.query();
    } catch (err) {
      console.warn(
        `[E2EE] ${label}: failed to list E2EE channels for redistribute:`,
        err
      );
      return;
    }
    for (const channelId of channelIds) {
      try {
        // Rotate first so peers receive a brand-new chain rather than a
        // re-SKDM of the same chainKey under our new identity.
        await rotateOutboundChannelChain(
          channelId,
          instanceOwnUserId,
          instanceStore
        );
        await ensureChannelSenderKey(channelId, instanceOwnUserId, {
          store: instanceStore,
          trpc: instanceTrpc
        });
      } catch (err) {
        console.warn(
          `[E2EE] ${label}: failed to redistribute for channel ${channelId}:`,
          err
        );
      }
    }
  };

  // Home instance — uses Redux's ownUserId since home is always the
  // active source-of-truth for the user's primary identity.
  const homeOwnUserId = state.server.ownUserId;
  if (homeOwnUserId) {
    await redistributeForInstance(
      'home',
      getHomeTRPCClient(),
      signalStore,
      homeOwnUserId
    );
  }

  // Federated instances. Each entry carries its own ownUserId (cached
  // at federated joinServer time). For entries missing it (e.g. loaded
  // from localStorage but never connected this session), fall back to
  // a lightweight users.getMyId query and cache the result.
  for (const entry of state.app.federatedServers) {
    const remoteTrpc = connectionManager.getRemoteTRPCClient(
      entry.instanceDomain
    );
    if (!remoteTrpc) continue;

    let federatedOwnUserId = entry.ownUserId;
    if (federatedOwnUserId === undefined) {
      try {
        const result = await remoteTrpc.users.getMyId.query();
        federatedOwnUserId = result.userId;
        reduxStore.dispatch(
          appSliceActions.setFederatedOwnUserId({
            instanceDomain: entry.instanceDomain,
            ownUserId: federatedOwnUserId
          })
        );
      } catch (err) {
        // Older federated peer without users.getMyId — skip; the next
        // user-initiated visit to this instance will populate ownUserId
        // via the joinServer path.
        console.warn(
          `[E2EE] federated ${entry.instanceDomain}: users.getMyId unavailable, skipping redistribute:`,
          err
        );
        continue;
      }
    }

    const federatedStore = getStoreForInstance(entry.instanceDomain);
    await redistributeForInstance(
      `federated ${entry.instanceDomain}`,
      remoteTrpc,
      federatedStore,
      federatedOwnUserId
    );
  }
}

// --- DM Group E2EE (Sender Keys, Phase B) ---

/**
 * Get-or-create our outbound chain for a DM group, then SKDM the
 * latest distribution to every other member who hasn't received it.
 * Honors a dirty marker (B4 lazy rotation) and rotates if set.
 *
 * Member list is supplied by the caller — DMs don't have a server
 * `getVisibleUsers` route; the channel's stored member list is the
 * authoritative source.
 */
export async function ensureDmGroupSenderKey(
  dmChannelId: number,
  ownUserId: number,
  memberIds: number[]
): Promise<void> {
  if (!(await hasKeys())) return;
  const trpc = getHomeTRPCClient();
  if (!trpc) return;

  let chain;
  if (await signalStore.isChainDirty(KIND_DM, dmChannelId)) {
    chain = await rotateOutboundDmChain(dmChannelId, ownUserId);
    await signalStore.clearChainDirty(KIND_DM, dmChannelId);
  } else {
    chain = await getOrCreateOutboundDmChain(dmChannelId, ownUserId);
  }

  await distributeChainToMembers({
    kind: KIND_DM,
    scopeId: dmChannelId,
    ownUserId,
    store: signalStore,
    trpc,
    distribution: chain.buildDistribution(),
    getMembers: async () => memberIds,
    send: async (distributions) => {
      await trpc.dms.distributeSenderKeys.mutate({
        dmChannelId,
        senderKeyId: chain.state.senderKeyId,
        distributions
      });
    }
  });
}

/**
 * Forced rotation entry point — used when a DM-group member is
 * removed by a path that doesn't first set the dirty marker (e.g.
 * the member-removal subscription handler fires this directly).
 */
export async function rotateDmGroupSenderKey(
  dmChannelId: number,
  ownUserId: number,
  remainingMemberIds: number[]
): Promise<void> {
  await rotateOutboundDmChain(dmChannelId, ownUserId);
  await signalStore.clearChainDirty(KIND_DM, dmChannelId);
  await ensureDmGroupSenderKey(dmChannelId, ownUserId, remainingMemberIds);
}

const activeDmSenderKeyFetches = new Map<
  number | undefined,
  Promise<void>
>();

export function fetchAndProcessPendingDmSenderKeys(
  dmChannelId?: number
): Promise<void> {
  const existing = activeDmSenderKeyFetches.get(dmChannelId);
  if (existing) return existing;
  const promise = doFetchAndProcessPendingDmSenderKeys(dmChannelId).finally(
    () => activeDmSenderKeyFetches.delete(dmChannelId)
  );
  activeDmSenderKeyFetches.set(dmChannelId, promise);
  return promise;
}

async function doFetchAndProcessPendingDmSenderKeys(
  dmChannelId?: number
): Promise<void> {
  const trpc = getHomeTRPCClient();
  if (!trpc) return;
  const pending = await trpc.dms.getPendingSenderKeys.query({ dmChannelId });

  const processedIds: number[] = [];
  for (const key of pending) {
    try {
      const decryptedJson = await decryptMessage(
        key.fromUserId,
        key.distributionMessage
      );
      const distribution = JSON.parse(decryptedJson) as SenderKeyDistribution;
      await acceptInboundDmChain(
        key.dmChannelId,
        key.fromUserId,
        distribution
      );
      processedIds.push(key.id);
      // Phase B follow-up: re-decrypt anything from this sender stuck
      // on '[Unable to decrypt]' before the SKDM landed.
      retryFailedDmDecrypts(key.dmChannelId, key.fromUserId).catch(
        (err) => {
          console.warn('[E2EE/DM] Retry-decrypt loop errored:', err);
        }
      );
    } catch (err) {
      console.warn(
        `[E2EE/DM] Failed to process sender key from user ${key.fromUserId}:`,
        err
      );
    }
  }

  if (processedIds.length > 0) {
    try {
      await trpc.dms.acknowledgeSenderKeys.mutate({ ids: processedIds });
    } catch {
      // Non-fatal — keys will redeliver and dedupe on next pull.
    }
  }
}

export async function encryptDmGroupMessage(
  dmChannelId: number,
  ownUserId: number,
  payload: E2EEPlaintext
): Promise<string> {
  await ensureE2EEKeys();
  const plaintext = JSON.stringify(payload);
  const wire = await encryptDmGroupWithChain(
    dmChannelId,
    ownUserId,
    plaintext
  );
  captureOwnPlaintextByCiphertext(wire, plaintext);
  return wire;
}

export async function decryptDmGroupMessage(
  dmChannelId: number,
  fromUserId: number,
  encryptedContent: string,
  messageId?: number
): Promise<E2EEPlaintext> {
  // Own-message fast path — see encryptDmGroupMessage. Same shape
  // as decryptChannelMessage's own-cache: chain ratchet has moved
  // past the iteration we just sent, so subscription-echo decrypt
  // through the chain throws.
  const cachedByCiphertext = takeOwnPlaintextByCiphertext(encryptedContent);
  if (cachedByCiphertext !== undefined) {
    if (messageId !== undefined) {
      void persistOwnPlaintextById(messageId, cachedByCiphertext);
    }
    return JSON.parse(cachedByCiphertext) as E2EEPlaintext;
  }
  if (messageId !== undefined) {
    const persisted = await getPersistedOwnPlaintextById(messageId);
    if (persisted !== undefined) {
      return JSON.parse(persisted) as E2EEPlaintext;
    }
  }

  const decoded = decodeWire(encryptedContent);
  const MAX_RETRIES = 3;
  const BASE_DELAY = 500;
  for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
    if (await hasDmChain(dmChannelId, fromUserId, decoded.senderKeyId)) break;
    await fetchAndProcessPendingDmSenderKeys(dmChannelId);
    if (await hasDmChain(dmChannelId, fromUserId, decoded.senderKeyId)) break;
    if (attempt < MAX_RETRIES) {
      await new Promise((r) =>
        setTimeout(r, BASE_DELAY * Math.pow(2, attempt))
      );
    }
  }

  let plaintext: string;
  try {
    plaintext = await decryptDmGroupWithChain(
      dmChannelId,
      fromUserId,
      encryptedContent
    );
  } catch (err) {
    if (err instanceof MissingDmChainError) {
      await fetchAndProcessPendingDmSenderKeys(dmChannelId);
      plaintext = await decryptDmGroupWithChain(
        dmChannelId,
        fromUserId,
        encryptedContent
      );
    } else {
      throw err;
    }
  }
  // Persist the plaintext keyed by messageId — sender-key chains
  // advance on decrypt, so subsequent re-fetches of the same wire
  // would throw "replay" without this cache.
  if (messageId !== undefined) {
    void persistOwnPlaintextById(messageId, plaintext);
  }
  return JSON.parse(plaintext) as E2EEPlaintext;
}

/**
 * B4 hook — the kick/leave/role-change subscription handlers call
 * this with `(kind, scopeId)` of the affected scope. The next encrypt
 * pass will rotate (new senderKeyId, new chain, distribute SKDM only
 * to members still visible).
 *
 * Idempotent — repeated calls before the next encrypt are coalesced
 * into a single rotation by `ensureChannelSenderKey` /
 * `ensureDmGroupSenderKey`.
 */
export async function markChainForRotation(
  kind: ChainKind,
  scopeId: number
): Promise<void> {
  const store = kind === KIND_DM ? signalStore : getActiveStore();
  await store.markChainDirty(kind, scopeId);
}

// Re-export types and utilities
export type { E2EEPlaintext, PreKeyBundle } from './types';
export { encryptFile, decryptFile } from './file-crypto';
export { hasKeys, getIdentityPublicKey } from './signal-protocol';
export { signalStore, getActiveStore, getStoreForInstance } from './store';
